/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.8
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

type PayablesLedger struct {
	Date string `json:"date"`
	LedgerType string `json:"ledger_type"`
	Narrative string `json:"narrative"`
	Amount float64 `json:"amount"`
	Reconciled bool `json:"reconciled"`
	JournalId int64 `json:"journal_id,omitempty"`
	SalesInvoiceId int64 `json:"sales_invoice_id,omitempty"`
}
