/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.2
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

// Production Order Details
type ProductionOrder struct {
	Priority int32 `json:"priority"`
	Quantity int32 `json:"quantity"`
	Notes string `json:"notes,omitempty"`
	BillOfMaterialsId int64 `json:"bill_of_materials_id,omitempty"`
	SalesOrderId int64 `json:"sales_order_id,omitempty"`
	Id int64 `json:"id,omitempty"`
	WorkCentreGroupId int64 `json:"work_centre_group_id,omitempty"`
	JobOrder int64 `json:"job_order,omitempty"`
	State string `json:"state,omitempty"`
	Logs []ProductionOrderLog `json:"logs,omitempty"`
}
