/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.8
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

import (
	"time"
)

// Work Centre Details
type WorkCentre struct {
	Id int64 `json:"id,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	WorkCentreGroupId int64 `json:"work_centre_group_id,omitempty"`
	Location string `json:"location,omitempty"`
	State int64 `json:"state,omitempty"`
	ProductionOrderId int64 `json:"production_order_id,omitempty"`
}
