/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.2
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

import (
	"time"
)

type PartnerNote struct {
	Date time.Time `json:"date"`
	Author string `json:"author"`
	Note string `json:"note"`
}
