/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.2
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

import (
	"time"
)

type ProductionOrderLog struct {
	Date time.Time `json:"date"`
	Member string `json:"member"`
	Message string `json:"message"`
}
