/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.8
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

// Partner Details
type PartnerInput struct {
	Name string `json:"name"`
	CurrencyCode string `json:"currency_code"`
	NetTerms int32 `json:"net_terms,omitempty"`
	CreditLimit float64 `json:"credit_limit,omitempty"`
	PartnerVat string `json:"partner_vat,omitempty"`
}
