/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.2
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

// Production Order Details
type ProductionOrderInput struct {
	Priority int32 `json:"priority"`
	Quantity int32 `json:"quantity"`
	Notes string `json:"notes,omitempty"`
	BillOfMaterialsId int64 `json:"bill_of_materials_id,omitempty"`
	SalesOrderId int64 `json:"sales_order_id,omitempty"`
}
