/*
 * Beanie ERP API
 *
 * An API specification for interacting with the Beanie ERP system
 *
 * API version: 0.2
 * Contact: dev@bean.ie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package beanie

// Partner Details
type Partner struct {
	Name string `json:"name"`
	CurrencyCode string `json:"currency_code"`
	NetTerms int32 `json:"net_terms,omitempty"`
	CreditLimit float64 `json:"credit_limit,omitempty"`
	PartnerVat string `json:"partner_vat,omitempty"`
	Id int64 `json:"id,omitempty"`
	Code string `json:"code,omitempty"`
	State string `json:"state,omitempty"`
	CreditHold bool `json:"credit_hold,omitempty"`
	Balance float64 `json:"balance,omitempty"`
	AddressIds []int32 `json:"address_ids,omitempty"`
	Notes []PartnerNote `json:"notes,omitempty"`
	ReceivablesLedgers []ReceivablesLedger `json:"receivables_ledgers,omitempty"`
	PayablesLedgers []PayablesLedger `json:"payables_ledgers,omitempty"`
}
